# Required to store and manage the logs generated by your containerized applications in a log group at AWS Cloudwatch.
resource "aws_cloudwatch_log_group" "cluster_lg" {
  name = var.log_group

  tags = {
    Project     = var.project_name
    Environment = var.environment
  }
}
