name: Create AWS Route53 Hosted Zone

on:
  workflow_dispatch: # Manual trigger

env:
  TERRAFORM_VERSION: 1.5.7
  AWS_REGION: eu-west-1

jobs:
  setup-terraform-state-bucket:
    uses: ./.github/workflows/backend_setup.yaml # reusable workflow
    with:
      github_head_commit_message: ${{ github.event.head_commit.message }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  create-hosted-zone:
    name: Create AWS Route53 Hosted Zone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: deployment/hosted_zone

      - name: Validate IaC changes
        run: terraform plan
        working-directory: deployment/hosted_zone

      - name: Create AWS Route53 Hosted Zone
        run: terraform apply -auto-approve
        working-directory: deployment/hosted_zone